### ISSUE TITLE
Hello, how to deploy this interface to a separate server, sometimes the network is slow.

### ISSUE THREAD

**Issue by chengfeng0113** [uetchy/math-api#130]
Hello, how to deploy this interface to a separate server, sometimes the network is slow.

**Comment by uetchy** [comment]
Added standalone server script for Math API.

https://github.com/uetchy/math-api/commit/b6ed931df6110f452cc47f88a3741fd61aef7b45

You can run the app on your machine:

```
ts-node server.ts
```

**Comment by chengfeng0113** [comment]
> Added standalone server script for Math API.
> 
> [b6ed931](https://github.com/uetchy/math-api/commit/b6ed931df6110f452cc47f88a3741fd61aef7b45)
> 
> You can run the app on your machine:
> 
> ```
> PORT=3000 ts-node server.ts
> ```

Thank you very much. It has been deployed.
