### ISSUE TITLE
Brackets are not escaped properly

### ISSUE THREAD

**Issue by Long0x0** [uetchy/math-api#224]
here 
https://github.com/uetchy/math-api/blob/11ac120a3919ed2129b00eedcd0954dfe6b6b30a/index.html#L206-L208

should be `.replace(/\(/g, "%28").replace(/\)/g, "%29")` to replace all brackets.

**Comment by uetchy** [comment]
@Long0x0 Thank you for pointing out that! Are you willing to send a PR for this? It would be helpful.

**Comment by Long0x0** [comment]
ok, I have created it.

**Comment by uetchy** [comment]
@Long0x0 Thank you for the patch⚡️

<https://github.com/uetchy/math-api#contributors->
