### ISSUE TITLE
Math “+” sign cannot be rendered

### ISSUE THREAD

**Issue by ericliyee** [uetchy/math-api#279]
https://math.vercel.app/?from=\sum^{N}_{i}x_i\times(4+5)
the "+" of "(4+5)" expression can't be rendered.

**Comment by slig** [comment]
Hi, you have to escape everything in the URL, specially the plus sign.

See https://math.vercel.app/?from=%5Csum%5E%7BN%7D_%7Bi%7Dx_i%5Ctimes(4%2B5)&color=red

**Comment by ericliyee** [comment]
thanks a lot  :-)
