### ISSUE TITLE
Does not follow Github theme

### ISSUE THREAD

**Issue by kozross** [uetchy/math-api#281]
If I have an inclusion like below in a Github wiki page:

```md
![Equation](https://math.vercel.app?from=%5Cleft%28%5Cbegin%7Barray%7D%7Bccccc%7D%0A1%20%26%202%20%26%203%20%26%204%20%26%205%20%5C%5C%0A2%20%26%205%20%26%204%20%26%203%20%26%201%0A%5Cend%7Barray%7D%5Cright%29.svg)
```

I get this on a Github light theme:

![Screenshot from 2022-04-07 08-48-11](https://user-images.githubusercontent.com/8463904/162068117-3e86c873-ba49-46db-932a-bd81e9f393fb.png)

But it works fine on a dark one:

![Screenshot from 2022-04-07 08-49-07](https://user-images.githubusercontent.com/8463904/162068266-9e939fea-bfff-44a3-b43f-de7fbf4ff11e.png)

I can forcibly set the text colour, but this feels like a bug, plus there isn't really a good choice of colour that would work on both light and dark themes.

**Comment by uetchy** [comment]
Is your system theme in dark mode?

**Comment by kozross** [comment]
@uetchy Yes, but this happens even if I set Github to ignore it.

**Comment by uetchy** [comment]
Hmm what should we do? Basically two options

1. Ditch automatic color switching & add background
2. Grey color as a default

**Comment by kozross** [comment]
Being able to force a background colour would fix this issue for me.

**Comment by uetchy** [comment]
Just found this option in GitHub docs. Maybe we can also offer more fine-grained Markdown tags for GitHub users in the online editor.
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

**Comment by uetchy** [comment]
```md
![Dark](https://math.vercel.app?from=\LaTeX&color=white#gh-dark-mode-only)
![Light](https://math.vercel.app?from=\LaTeX&color=black#gh-light-mode-only)
```

![Dark](https://math.vercel.app?from=\LaTeX&color=white#gh-dark-mode-only)
![Light](https://math.vercel.app?from=\LaTeX&color=black#gh-light-mode-only)

^Maybe this only works in actual Markdown files?

**Comment by kozross** [comment]
This also doesn't work on Github wiki pages.

**Comment by uetchy** [comment]
<img width="986" alt="Screen Shot 2022-04-12 at 16 54 05" src="https://user-images.githubusercontent.com/431808/162910067-7807a63c-60b6-4610-8d51-c2f96e5526e0.png">
<img width="886" alt="Screen Shot 2022-04-12 at 16 54 25" src="https://user-images.githubusercontent.com/431808/162910083-fcbef64e-b669-40ed-8fec-a497bbfd9a65.png">

**Comment by uetchy** [comment]
Released
