### ISSUE TITLE
Support xrightarrow

### ISSUE THREAD

**Issue by vimaxwell** [uetchy/math-api#32]
I got trouble with xrightarrow formula

**Comment by uetchy** [comment]
Is it supported in MathJax? I use MathJax for rendering LaTeX so if it doesn’t have support for xrightarrow, Math API cannot handle it.

**Comment by vimaxwell** [comment]
I filled this formula `$$S + 3F2 \xrightarrow{{{t}^{0}}}SF_6$$` in demo page https://www.mathjax.org/#demo and it works.

**Comment by uetchy** [comment]
I've figured out that all extensions are missing in the API. Fixed in https://github.com/uetchy/math-api/commit/7dcd144da7930ea767c71831484e57dcbed363fe.
Now all AMS and other extensions are available to use.

Just want to say thank you for letting me know about this.
