### ISSUE TITLE
Error with () on markdown code

### ISSUE THREAD

**Issue by insuns** [uetchy/math-api#34]
Like this:
```
M_{Total} = \displaystyle\sum_{futures=cu, al\dots }^m\bigg(\displaystyle\sum_{day=0}^n{M_{m}}\bigg)
```
![Equation](https://math.now.sh?from=M_%7BTotal%7D%20%3D%20%5Cdisplaystyle%5Csum_%7Bfutures%3Dcu%2C%20al%5Cdots%20%7D%5Em%5Cbigg(%5Cdisplaystyle%5Csum_%7Bday%3D0%7D%5En%7BM_%7Bm%7D%7D%5Cbigg))

And, how can run the program on docker?

**Comment by insuns** [comment]
sorry, just some markdown editor has this issue. but replace `( ` to `%28` and  `)`  to `%29` will be better.

**Comment by uetchy** [comment]
@insuns Thank you for the report and fixed now.

**Comment by uetchy** [comment]
> And, how can run the program on docker?
Install now via `npm i -g now` and run `now dev` to launch local instance.

**Comment by insuns** [comment]
Thank you very much for your help.
